### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by gordalina** [gordalina/standing-desk#1]
## Inspiration

- https://www.ikea.com/us/en/p/skarsta-desk-sit-stand-white-s59324818/
- https://hackaday.com/2019/01/23/motorizing-an-ikea-skarsta-table/
- https://github.com/aenniw/ARDUINO/tree/master/skarsta

## Info
- 80 turns to go from bottom to ideal position
- 107 turns total from bottom to top.
- target 180RPM @ 30kg.cm

## Parts
- https://www.banggood.com/DC-12V-180RPM-Geared-Motor-High-Torque-Gear-Reducer-Motor-p-1068573.html?p=7W02096203810201609O&stayold=1&curwarehouse=CN&cur_warehouse=CN
- https://www.frys.com/product/9869895?site=sr:SEARCH:MAIN_RSLT_PG
- https://www.salpurh.com/index.php?main_page=product_info&products_id=416503

## Parts List
- [ ] Motor (tbd)
- [ ] Power supply (tbd)
- [ ] [Rotary Encoder](https://www.salpurh.com/index.php?main_page=product_info&products_id=416503)
- [ ] [Belt](https://www.aliexpress.com/item/32883539514.html)
- [ ] [PSU Jack](https://www.ebay.com/itm/10pcs-DC-005-Power-Supply-Jack-Socket-Female-PCB-Mount-Connector-5-5mm-x-2-1mm/263403309838)
- [ ] [on/off switch](https://www.ebay.com/itm/10Pcs-12V-2-Pin-Car-Boat-Round-Dot-Light-ON-OFF-Rocker-Toggle-Switch-Tool-Black/382170389677)
- [ ] [H bridge](https://www.ebay.com/itm/Double-BTS7960B-DC-43A-Stepper-Motor-Driver-H-Bridge-PWM-For-Arduino-Smart-Car-/200950936475)
- [ ] [Fuse](https://www.aliexpress.com/item/32897554363.html)
- [ ] [Fuse mount](https://www.aliexpress.com/item/32881363210.html)
- [ ] [Shaft coupling](https://www.ebay.com/itm/2-3-4-5-6-7-8mm-Aluminum-Flexible-Shaft-Coupling-Rigid-Coupler-Motor-Connector-/162597005262) 6-7mm

## 3d print
- [ ] [Pulley](https://www.thingiverse.com/thing:3227567)
- [ ] [Motor pulley](https://github.com/aenniw/ARDUINO/blob/master/skarsta/models/motor-pulley.stl)
- [ ] [Encoder Pulley](https://github.com/aenniw/ARDUINO/blob/master/skarsta/models/encoder-pulley.stl)

## Other
- [ ] Soldering iron
- [ ] Solder
- [ ] Breadboard
- [ ] Wires
- [ ] Wire strippers
- [ ] [Multimeter](http://www.engblaze.com/the-best-multimeter-for-beginners/#:~:text=Our%20pick%20for%20the%20best,enough%20for%20most%20hobby%20work.)

## Measurements
- Initial measurement was 600g with a lever 12cm long
- 0.48N force of the lever
- 0.06 torque of the lever

## Questions
- [ ] How do we decide on a h-bridge/relay circuit design, how does that affect the motor we can use, and how can we choose said motor based on the design.
- [ ] What soldering iron to get

## Todo
- [ ] Move the crank holder out, closer to the edge
- [ ] Crankshaft it wonky
